#!/usr/bin/env python3
"""Generate data/terms.js, data/stories.js and data/questions.js from the spec.

The spec (docs/claude-study-website-design.md) is the single source of truth for
study-guide wording and the 170 hand-written questions. Enrichment that the spec
describes in prose (clusters, images, mnemonics, heads-up notes, media for picture
and map questions) lives in the dicts below.

Run:  python3 tools/build_data.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = (ROOT / "docs" / "claude-study-website-design.md").read_text(encoding="utf-8")


def section(start, end):
    i = SPEC.index(start)
    j = SPEC.index(end, i + len(start))
    return SPEC[i:j]


def inline_md(s):
    s = re.sub(r"\*\*\*(.+?)\*\*\*", r"<b><i>\1</i></b>", s)
    s = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", s)
    s = re.sub(r"(?<![\w*])\*(?!\s)(.+?)(?<!\s)\*(?![\w*])", r"<i>\1</i>", s)
    return s.replace("</b></i>", "</i></b>")


def plain(s):
    s = re.sub(r"\*\*(.+?)\*\*", r"\1", s)
    s = re.sub(r"\*(.+?)\*", r"\1", s)
    return s.strip()


def write_js(name, var, data):
    out = ROOT / "data" / name
    body = json.dumps(data, ensure_ascii=False, indent=1)
    out.write_text(f"// Generated by tools/build_data.py from docs/claude-study-website-design.md\nwindow.{var} = {body};\n", encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)}")


# ---------------------------------------------------------------- terms
CLUSTER = {}
for c, ids in {
    "c1": "myth legends folktale anthropomorphism etiological eponymous syncretism cosmogony theogony creation greece",
    "c2": "chaos gaea tartarus uranus titans cyclopes hundred cronus furies typhoeus metis oceanus helios atlas succession titanomachy theogony_src",
    "c3": "anu tiamat marduk inanna flood mesopotamia enuma gilgamesh",
    "c4": "prometheus epimetheus pandora deucalion fiveages lycaon prometheus_bound works",
    "c5": "zeus hera hestia poseidon hades ganymede xenia dike achilles priam olympus homer",
    "c6": "leto apollo artemis python pythia daphne coronis asclepius hyacinth cassandra sibyl actaeon callisto orion niobe delos delphi hymns",
    "c7": "hermes maia pan priapus caduceus herm apotropaic lyre panpipes hermaphroditus petasos nymphs",
    "c8": "aphrodite anchises adonis myrrha pygmalion eros hephaestus ares thetis aeneas cyprus metamorphoses",
    "c9": "athena aegis arachne athens",
}.items():
    for i in ids.split():
        CLUSTER[i] = c

IMAGE = {
    "apollo": "08-apollo-kylix.jpg", "hermes": "09-hermes-lekythos.jpg", "pan": "11-pan-mosaic.jpg",
    "hephaestus": "12-hephaestus-thetis.jpg", "aphrodite": "13-aphrodite-rising.jpg",
    "athena": "15-athena-panathenaic.jpg", "zeus": "03c-zeus-detail.jpg", "niobe": "01-niobids.jpg",
    "tiamat": "02-tiamat-marduk.jpg", "marduk": "02-tiamat-marduk.jpg", "typhoeus": "03b-typhoeus-detail.jpg",
    "atlas": "04-atlas-prometheus.jpg", "prometheus": "04-atlas-prometheus.jpg",
    "pandora": "06-birth-of-pandora.jpg", "epimetheus": "06-birth-of-pandora.jpg",
    "hera": "07-wedding-hera-zeus.jpg", "aegis": "15-athena-panathenaic.jpg",
    "caduceus": "09-hermes-lekythos.jpg", "petasos": "09-hermes-lekythos.jpg", "lyre": "08-apollo-kylix.jpg",
    "thetis": "12-hephaestus-thetis.jpg", "metis": "14-birth-of-athena.jpg", "artemis": "01-niobids.jpg",
    "coronis": "08-apollo-kylix.jpg",
    # slide images
    "delos": "../slide-images/delos-temple.jpg", "poseidon": "../slide-images/athena-poseidon-vase.jpg",
    "athens": "../slide-images/athena-poseidon-vase.jpg", "helios": "../slide-images/helios-chariot.png",
    "deucalion": "../slide-images/genealogy-deucalion-hellen.png", "eponymous": "../slide-images/genealogy-deucalion-hellen.png",
    "flood": "../slide-images/flood-gilgamesh.jpg", "gilgamesh": "../slide-images/flood-gilgamesh.jpg",
    "herm": "../slide-images/pan-chasing-shepherd.jpg",
}

M = {
    "kids": "Cronus' children — “He Did Have Hungry Powerful Zeus” = Hestia, Demeter, Hera, Hades, Poseidon, Zeus.",
    "haa": "Immune to Aphrodite = “the 3 virgins”, HAA: Hestia, Athena, Artemis (“no children”).",
    "haap": "Hephaestus traps “HAAP”: Hera, Ares, Aphrodite, Prometheus.",
    "cc": "Cyclopes Craft thunderbolts; Hundred-Handers Hurl boulders.",
    "rej": "Apollo's A-list rejections: Sibyl, Cassandra, Daphne (rejected); Coronis (cheated).",
    "ages": "Five Ages: “Good Students Become Happy Intellectuals” = Gold, Silver, Bronze, Heroes, Iron.",
    "names": "Names: Pro-metheus = before-thought; Epi-metheus = after-thought; Pan-dora = all-gifts; A-des (Hades) = un-seen.",
    "dp": "Deucalion & Pyrrha = D&P = “Drop Pebbles” — the only flood survivors who make people from stones.",
    "pan": "Pan → panic; Syrinx → syringe (tube) / pan pipes.",
    "pyg": "Pygmalion = Cyprus = Aphrodite's island.",
    "o12": "Olympian 12: Zeus, Hera, Poseidon, Demeter, Hestia (sometimes replaced by Dionysus), Athena, Apollo, Artemis, Ares, Aphrodite, Hephaestus, Hermes.",
}
MNEMONIC = {
    "cronus": "kids", "titans": "kids", "hestia": "haa", "athena": "haa", "artemis": "haa",
    "hephaestus": "haap", "cyclopes": "cc", "hundred": "cc", "titanomachy": "cc",
    "cassandra": "rej", "sibyl": "rej", "daphne": "rej", "coronis": "rej", "fiveages": "ages",
    "prometheus": "names", "epimetheus": "names", "pandora": "names", "hades": "names",
    "deucalion": "dp", "flood": "dp", "pan": "pan", "panpipes": "pan", "pygmalion": "pyg", "cyprus": "pyg",
    "olympus": "o12", "zeus": "o12",
}

HEADSUP = {
    "niobe": "Study guide says twelve children (Homer); Ovid says fourteen. On the exam → twelve.",
    "pygmalion": "Study guide says marble; Ovid says ivory. Either way: perfect woman statue, Cyprus, brought to life by Aphrodite.",
    "aphrodite": "Hesiod = born from Uranus' genitals/sea foam; Homer = daughter of Zeus & Dione. The image (rising from the sea) = Hesiod's version.",
    "hephaestus": "Hesiod = Hera alone; Homer = Zeus & Hera. Either way: “Hera is the unhappy mother of Hephaestus.”",
    "hera": "Hesiod = Hera alone bore Hephaestus; Homer = Zeus & Hera. Either way: “Hera is the unhappy mother of Hephaestus.”",
    "eros": "Primordial force (Hesiod) and son of Aphrodite (later) — the guide accepts both.",
    "pandora": "Pandora's “box” is really a jar (pithos).",
    "helios": "Separate from Apollo early; identified with him later → evidence that gods change over time.",
    "tartarus": "Both a primordial being (monster) and a place in the underworld.",
}

# extra elaboration facts beyond the table's "key extra facts" column (from the §4.2 clusters)
EXTRA_MORE = {
    "zeus": ["Roman Jupiter; name = “bright” (sky)", "Defeats Typhoeus with thunderbolts; divides world: Zeus sky, Poseidon sea, Hades underworld"],
    "poseidon": ["Gave a salt spring in the contest for Athens; Athena gave the olive tree and won", "Horses; trident"],
    "hermes": ["Invents the lyre on his first day, steals Apollo's cattle (driving them backward), climbs back into his cradle", "Reconciles with Apollo by giving him the lyre"],
    "apollo": ["Loves go badly: Daphne, Coronis, Cassandra, Sibyl, Hyacinth", "Raven turned black for reporting Coronis"],
    "artemis": ["Brings sudden death to women with her arrows; helps in childbirth"],
    "pan": ["From Arcadia; chases travelers/shepherds → “panic”"],
    "prometheus": ["Trick at Mecone: Zeus picks the bones wrapped in fat", "Steals fire in a fennel stalk", "Bound by Hephaestus in Aeschylus' Prometheus Bound"],
    "pandora": ["Crafted by Hephaestus; Hermes gives deceitful mind and speech", "Opens the jar (pithos); Hope stays inside"],
    "deucalion": ["Deucalion = son of Prometheus; Pyrrha = daughter of Epimetheus & Pandora", "Land on Mt. Parnassus; “throw the bones of your great mother” = stones", "Unique to their flood story: people recreated from stones"],
    "cronus": ["Rhea gives him a stone in swaddling clothes instead of Zeus"],
    "hundred": ["Also called Hecatonchires"],
    "furies": ["Punish people who kill their kin (and oath-breakers)"],
    "leto": ["Promised Delos that Apollo would build a temple there"],
    "asclepius": ["Raised by the centaur Chiron"],
    "adonis": ["Lamented in the annual Adonia ritual"],
    "anchises": ["Aphrodite visits his shepherd's hut (good xenia) — Homeric Hymn to Aphrodite"],
    "lycaon": ["King of Arcadia; the ultimate violation of xenia"],
    "hades": ["Name means “invisible / the unseen one”"],
    "hera": ["Hand-clasping in art = marriage", "Persecutes Leto, Callisto"],
    "athena": ["Iconography: helmet, spear, shield, aegis; owl; olive", "Virgin (Parthenos → Parthenon)"],
    "aphrodite": ["Cannot overpower Hestia, Athena, Artemis", "Zeus made her love Anchises to stop her gloating"],
    "typhoeus": ["Gaea's last challenge to Zeus; hurled into Tartarus"],
    "tiamat": ["With Apsu (fresh water) produces the gods in the Enuma Elish"],
    "marduk": ["Kills Tiamat with winds + arrow; humans made from Kingu's blood"],
    "helios": ["Son of the Titan Hyperion; epithet Phoebus (“bright”) later shared with Apollo"],
    "eros": ["In Hesiod appears right after Chaos, Gaea, Tartarus"],
    "lyre": ["Made from a tortoise shell on Hermes' first day"],
    "herm": ["Apotropaic; seen to the right of Pan chasing a shepherd (review slide)"],
    "xenia": ["Good: Achilles gives Priam food and a bed; Anchises welcomes Aphrodite", "Bad: Lycaon serves human flesh to Zeus"],
    "syncretism": ["Not deification (making someone a god) or catasterism (turning someone into a star)"],
    "anthropomorphism": ["anthropos “human” + morphē “shape”", "Not anthropology / anthropophagy / anthropometry"],
    "myth": ["A myth is the complex of all its variants — no version is more authentic"],
    "eponymous": ["Hellen's sons/grandsons (Dorus, Aeolus, Xuthus → Ion) name the dialect groups"],
    "creation": ["Birthing: Gaea + Uranus produce offspring (Hesiod)", "Crafting: Marduk shapes the cosmos from Tiamat; Prometheus molds humans; Hephaestus makes Pandora"],
    "fiveages": ["Gold → Silver → Bronze → Heroes (the one improvement) → Iron (our age)", "Hesiod, Works and Days; Ovid gives four metal ages, no heroes"],
    "flood": ["Pattern: human failure → mass destruction → survivors in a boat → repopulation", "Utnapishtim (Gilgamesh), Noah (Genesis), Deucalion & Pyrrha (Ovid)"],
    "succession": ["Each son overthrows the father; the mother helps", "Ends when Zeus swallows Metis"],
    "titanomachy": ["10-year war; Titans imprisoned in Tartarus"],
    "aegis": ["Goatskin chest-cape with snakes and the Gorgon's head"],
}


def parse_table(title_start, ncols):
    block = section(title_start, "\n### ")
    rows = []
    for line in block.splitlines():
        if not line.startswith("| ") or line.startswith("| id") or line.startswith("|---"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        rows.append(cells[:ncols])
    return rows


terms = []


def add_term(tid, name, cat, guide, more=None, roman=None, extra=False):
    t = {"id": tid, "term": name, "cat": cat, "guide": guide, "more": [m for m in (more or []) if m]}
    t["more"] += EXTRA_MORE.get(tid, [])
    if roman and roman not in ("—", name):
        t["roman"] = roman
    t["cluster"] = CLUSTER.get(tid, "")
    if tid in IMAGE:
        t["image"] = IMAGE[tid]
    if tid in MNEMONIC:
        t["mnemonic"] = M[MNEMONIC[tid]]
    if tid in HEADSUP:
        t["headsup"] = HEADSUP[tid]
    if extra:
        t["extra"] = True
    terms.append(t)


def split_facts(s):
    return [plain(x) for x in s.split(";")] if s and s != "—" else []


for tid, name, guide, facts, roman in parse_table("### 4.3", 5):
    add_term(tid, plain(name), "divinity", guide, split_facts(facts), roman)

for tid, name, guide, facts in parse_table("### 4.4", 4):
    extra = "*(extra" in name
    add_term(tid, plain(re.sub(r"\*\(.*?\)\*", "", name)), "mortal", guide, split_facts(facts), extra=extra)

for tid, name, guide in parse_table("### 4.5", 3):
    extra = "*(extra" in name
    add_term(tid, plain(re.sub(r"\*\(.*?\)\*", "", name)), "concept", guide, extra=extra)

# 4.6 places (guide wording from the study guide list)
for tid, name, guide, more in [
    ("athens", "Athens", "Athena's city", ["Athena beat Poseidon for its patronage (olive tree vs. salt spring)"]),
    ("cyprus", "Cyprus", "Aphrodite's island", ["Large island in the far east Mediterranean", "Aphrodite comes ashore here after her birth from the foam; Pygmalion's home"]),
    ("delos", "Delos", "birth place of Apollo/Artemis, shrine of Apollo", ["Small island in the Cyclades", "Leto promised it a temple (Homeric Hymn to Apollo)"]),
    ("delphi", "Delphi", "shrine and oracle of Apollo", ["Apollo kills Pytho(n) here; priestess = the Pythia", "On the slopes of Mt. Parnassus"]),
    ("greece", "Greece", "mainland + Aegean islands", ["Hellas; Greeks = Hellenes, after Hellen"]),
    ("mesopotamia", "Mesopotamia", "'between the rivers' Tigris & Euphrates (modern Iraq)", ["Babylon, Sumer; Enuma Elish, Gilgamesh, Inanna"]),
    ("olympus", "Mt. Olympus", "home of the 12 Olympian gods", ["N. Greece, Thessaly/Macedonia border"]),
]:
    add_term(tid, name, "place", guide, more)

# 4.7 source texts
for tid, name, guide, more, extra in [
    ("prometheus_bound", "Prometheus Bound", "Aeschylus (Athenian tragedian, 5th c. BCE)",
     ["Prometheus chained by Hephaestus; defiance of Zeus", "Prometheus knows a secret: Thetis' son will be greater than his father"], False),
    ("enuma", "Enuma Elish", "Babylonian creation epic: Marduk defeats Tiamat",
     ["Apsu & Tiamat produce the gods", "Marduk becomes king, makes the world from Tiamat's body", "“When on high…”; recited at the Babylonian New Year"], False),
    ("theogony_src", "Theogony (text)", "Hesiod (Boeotia, c. 700 BCE): origin of the gods",
     ["Chaos → Gaea…; succession myth", "Titanomachy; Typhoeus; Pandora (short version)"], False),
    ("works", "Works and Days", "Hesiod: Five Ages of Man, Pandora's jar",
     ["Justice (dikē); farming advice to brother Perses"], False),
    ("homer", "Iliad & Odyssey", "Homer (8th c. BCE)",
     ["Achilles & Priam — xenia (Iliad 24)", "Hephaestus makes Achilles' armor (Iliad 18)", "Ares & Aphrodite caught by Hephaestus (Odyssey 8)", "Oceanus as origin of the gods"], False),
    ("hymns", "Homeric Hymns", "anonymous hymns in “Homeric” style",
     ["Hymn to Apollo: birth on Delos, Delphi/Python", "Hymn to Hermes: lyre, cattle theft", "Hymn to Aphrodite: Anchises; the three goddesses she can't sway"], False),
    ("metamorphoses", "Metamorphoses", "Ovid (Roman, c. 8 CE; 15 books of transformations)",
     ["Lycaon & flood, Deucalion & Pyrrha", "Daphne; Actaeon; Arachne; Niobe", "Myrrha & Adonis; Pygmalion; Hermaphroditus; Syrinx; Callisto"], False),
    ("gilgamesh", "Epic of Gilgamesh", "Babylonian epic with the flood survivor Utnapishtim", [], True),
]:
    add_term(tid, name, "source", guide, more, extra=extra)

ids = [t["id"] for t in terms]
assert len(ids) == len(set(ids)), "duplicate term ids"
write_js("terms.js", "DATA_TERMS", terms)
print(f"  {len(terms)} terms:", {c: sum(t['cat'] == c for t in terms) for c in ['divinity', 'mortal', 'concept', 'place', 'source']})

# ---------------------------------------------------------------- stories
MINI = {  # 3 mini-check question numbers per cluster (from the bank)
    "c1": [3, 44, 23], "c2": [4, 25, 70], "c3": [80, 15, 7], "c4": [29, 104, 102],
    "c5": [10, 8, 22], "c6": [12, 11, 2], "c7": [30, 32, 149], "c8": [14, 24, 18], "c9": [20, 161, 162],
}
HEADSUP_CLUSTER = {
    "c2": ["tartarus", "eros", "helios"], "c4": ["pandora"], "c6": ["niobe"],
    "c8": ["pygmalion", "aphrodite", "hephaestus"],
}


def md_block_to_html(lines):
    html, stack = [], []  # stack of (indent, tag)
    for raw in lines:
        if not raw.strip():
            continue
        m = re.match(r"^(\s*)(- |\d+\. )(.*)$", raw)
        if not m:
            while stack:
                html.append(f"</{stack.pop()[1]}>")
            html.append(f"<p>{inline_md(raw.strip())}</p>")
            continue
        ind, marker, text = len(m.group(1)), m.group(2), m.group(3)
        tag = "ol" if marker[0].isdigit() else "ul"
        while stack and stack[-1][0] > ind:
            html.append(f"</{stack.pop()[1]}>")
        if not stack or stack[-1][0] < ind:
            html.append(f"<{tag}>")
            stack.append((ind, tag))
        elif stack[-1][1] != tag:
            html.append(f"</{stack.pop()[1]}>")
            html.append(f"<{tag}>")
            stack.append((ind, tag))
        html.append(f"<li>{inline_md(text)}</li>")
    while stack:
        html.append(f"</{stack.pop()[1]}>")
    return "\n".join(html)


stories = []
block = section("### 4.2", "### 4.3")
parts = re.split(r"^\*\*(C\d)\. (.+?)\*\*\s*$", block, flags=re.M)
for k in range(1, len(parts), 3):
    cid, title, body = parts[k].lower(), parts[k + 1], parts[k + 2]
    stories.append({
        "id": cid, "title": plain(title), "html": md_block_to_html(body.splitlines()),
        "check": [f"q{n:03d}" for n in MINI[cid]],
        "headsup": [HEADSUP[h] for h in HEADSUP_CLUSTER.get(cid, [])],
    })
assert len(stories) == 9, len(stories)
write_js("stories.js", "DATA_STORIES", stories)

# ---------------------------------------------------------------- questions
TAG_A = {1: "maps", 2: "apollo-artemis", 3: "myth-theory", 4: "succession", 5: "myth-theory", 6: "concepts",
         7: "flood", 8: "zeus-hera", 9: "concepts", 10: "zeus-hera", 11: "apollo-artemis", 12: "apollo-artemis",
         13: "maps", 14: "hephaestus-ares", 15: "mesopotamia", 16: "myth-theory", 17: "aphrodite", 18: "aphrodite",
         19: "images", 20: "athena", 21: "zeus-hera", 22: "zeus-hera", 23: "concepts", 24: "aphrodite",
         25: "succession", 26: "zeus-hera", 27: "images", 28: "images", 29: "prometheus", 30: "hermes-pan",
         31: "images", 32: "hermes-pan", 33: "apollo-artemis", 34: "images", 35: "images", 36: "images",
         37: "succession", 38: "flood", 39: "images", 40: "flood"}
TAG_B_OVERRIDE = {}
for rng, tag in [((41, 50), "myth-theory"), ((51, 56), "concepts"), ((89, 103), "prometheus"), ((104, 107), "flood"),
                 ((150, 154), "aphrodite"), ((155, 158), "hephaestus-ares"), ((168, 169), "images"), ((170, 170), "maps")]:
    for n in range(rng[0], rng[1] + 1):
        TAG_B_OVERRIDE[n] = tag

MEDIA = {
    1: {"map": {"marker": "delphi", "style": "star"}},
    13: {"map": {"marker": "delos", "style": "circle"}},
    19: {"img": "img15", "circle": "aegis"},
    27: {"img": "img08", "crop": "lyre"},
    28: {"img": "img03", "file": "03b-typhoeus-detail.jpg"},
    31: {"img": "img09"}, 34: {"img": "img01"}, 35: {"img": "img06"}, 36: {"img": "img14"},
    39: {"file": "../slide-images/pan-chasing-shepherd.jpg"},
    168: {"img": "img07"}, 169: {"img": "img04"},
    170: {"map": {"marker": "cyprus", "style": "circle"}},
}
EXTRA_TAGS = {19: ["athena"], 27: ["hermes-pan"], 31: ["hermes-pan"], 34: ["apollo-artemis"], 36: ["athena"],
              39: ["hermes-pan"], 28: ["succession"], 35: ["prometheus"], 168: ["zeus-hera"], 169: ["prometheus"],
              150: ["maps"], 119: ["maps"], 129: ["maps"], 163: ["maps"], 125: ["maps"],
              164: ["hermes-pan"], 165: ["aphrodite"]}
FIX_OPTS = {154: ["<b>Love, a primordial force / son of Aphrodite</b>", "god of war", "god of the sea", "goddess of the hearth"]}
WHY_B = {
    45: "Etiology = explains an origin: the laurel is sacred to Apollo because Daphne became a laurel.",
    49: "Crafting = a maker builds; birthing = sexual generation.",
    50: "Gaea + Uranus = birthing; Marduk, Hephaestus, Deucalion's stones are makings.",
    54: "Catasterism = made into a star (e.g., Callisto → Great Bear). Syncretism = blending gods.",
    58: "Chaos, Gaea, Tartarus, Eros are primordial; Zeus comes three generations later.",
    77: "Cronus swallowed the others; Rhea hid the youngest, Zeus, on Crete.",
    85: "Storm god defeats a serpent/chaos monster and becomes king.",
    92: "Etiology of sacrifice: humans keep the meat, burn bones for the gods.",
    102: "The Age of Heroes (Thebes, Troy) is the one improvement in the decline.",
    104: "Lycaon's feast is the ultimate violation of xenia → wolf → flood.",
    118: "Poseidon's salt spring lost to Athena's olive tree.",
    121: "Athena is Zeus' daughter (by Metis), not Cronus'.",
    126: "Leto promised Delos a temple → the sanctuary's origin story.",
    143: "Hermes made it from a tortoise shell and gave it to Apollo to reconcile.",
}

term_index = sorted(((t["term"], t) for t in terms if t["cat"] != "source"), key=lambda x: -len(x[0]))


def auto_why(qtext, correct):
    # prefer a term named in the correct answer, then one named in the question
    for hay in (plain(correct), plain(qtext)):
        for name, t in term_index:
            for alias in name.replace("&", "/").split("/"):
                alias = alias.split("(")[0].strip()
                if len(alias) >= 4 and re.search(r"\b" + re.escape(alias) + r"\b", hay):
                    return f"{t['term']}: {t['guide']}."
    return ""


questions = []


def add_q(n, tags, q, opts, ans, why):
    q = q.strip()
    if q[-1] not in "?:.…":
        q += " …"
    media = MEDIA.get(n, {})
    tags = list(dict.fromkeys(tags + EXTRA_TAGS.get(n, [])))
    qq = {"id": f"q{n:03d}", "tags": tags, "q": inline_md(q), "opts": [inline_md(o) for o in opts], "ans": ans,
          "why": inline_md(why)}
    qq.update(media)
    assert len(qq["opts"]) == 4, (n, opts)
    questions.append(qq)


# Section A
blockA = section("### 7.2", "### 7.3")
for line in blockA.splitlines():
    m = re.match(r"^(\d+)\. (.*)$", line)
    if not m:
        continue
    n, rest = int(m.group(1)), m.group(2)
    pieces = re.split(r"\s([ABCD])\) ", " " + rest)
    q = pieces[0]
    opts = [pieces[i + 1].strip() for i in range(1, len(pieces), 2)]
    why = ""
    tail = re.search(r"\s*\*\((.*?)\)\*\s*$", opts[-1])
    if tail:
        why = tail.group(1)
        why = why[5:] if why.startswith("why: ") else why
        opts[-1] = opts[-1][:tail.start()].strip()
    q = re.sub(r"\s*\*\(.*?\)\*", "", q).strip()
    ans = next(i for i, o in enumerate(opts) if "✔" in o)
    opts = [plain(o.replace("✔", "")).strip() for o in opts]
    correct = opts[ans]
    why = (f"{correct}. " + why).strip() if why else (f"{correct}. " + auto_why(q, correct)).strip()
    add_q(n, ["review", TAG_A[n]], q, opts, ans, why)

# Section B
blockB = section("### 7.3", "**Bonus Roman-name")
cur_tags = []
for line in blockB.splitlines():
    h = re.match(r"^\*\*.*\((`.*`)\)\*\*", line)
    if h:
        cur_tags = re.findall(r"`([\w-]+)`", h.group(1))
        continue
    m = re.match(r"^(\d+)\. (.*)$", line)
    if not m:
        continue
    n, rest = int(m.group(1)), m.group(2)
    media_note = re.search(r"^\*\((.*?)\)\*\s*", rest)
    if media_note:
        rest = rest[media_note.end():]
    parts = rest.split(" — ")
    q, opt_str, check = parts[0], parts[1], parts[2]
    why = parts[3] if len(parts) > 3 else ""
    # split on " / " outside **bold**
    protected = re.sub(r"\*\*(.+?)\*\*", lambda mm: "**" + mm.group(1).replace(" / ", "\u0000") + "**", opt_str)
    opts = [o.replace("\u0000", " / ").strip() for o in protected.split(" / ")]
    letter = re.search(r"✔([ABCD])", check).group(1)
    ans = "ABCD".index(letter)
    if n in FIX_OPTS:
        opts = FIX_OPTS[n]
    bold_idx = [i for i, o in enumerate(opts) if "**" in o or "<b>" in o]
    assert bold_idx == [ans], (n, opts, ans)
    opts = [plain(re.sub(r"</?b>", "", o)) for o in opts]
    tags = [TAG_B_OVERRIDE.get(n, cur_tags[0])]
    correct = opts[ans]
    if not why:
        why = WHY_B.get(n) or auto_why(q, correct)
    why = f"{correct[0].upper() + correct[1:]}. {why}".strip()
    add_q(n, tags, plain(q) if "*" in q else q, opts, ans, why)

nums = [int(q["id"][1:]) for q in questions]
assert nums == list(range(1, 171)), [n for n in range(1, 171) if n not in nums]
write_js("questions.js", "DATA_QUESTIONS", questions)
print(f"  {len(questions)} questions")
